### PR TITLE
Merge pkg/truncindex and pkg/symlink from moby/moby

### PR DESCRIPTION
**Pull request by dims**
We need to remove the recursive dependency of containerd<->moby/moby, containerd uses 2 packages from moby/moby. So to break the recursion, we need to move those two packages into a "neutral" repo. per the discussion in https://github.com/containerd/containerd/pull/4631, the idea was to preserve the git history of these two packages and merge them into this repository

cc @thaJeztah

### CODE REVIEW

**Comment by dims** [comment]
Notes on how the git history was pruned and grafted:
```
~/go/src/github.com/moby/moby> git checkout -b merging-some-branches
~/go/src/github.com/moby/moby> git filter-repo --path pkg/symlink --path pkg/truncindex
~/go/src/github.com/moby/moby> cd ../sys
~/go/src/github.com/moby/moby> git remote add patchy ../moby
~/go/src/github.com/moby/moby> git fetch patchy
~/go/src/github.com/moby/moby> git merge --allow-unrelated-histories --signoff -m "Merge pkg/(symlink|truncindex) from moby/moby into moby/sys" patchy/merging-some-branches
```

**Comment by dims** [comment]
@thaJeztah i don't feel that i should not try to "fix" the DCO failure, so leaving it as-is.

**Comment by thaJeztah** [comment]
Oh, thanks! Erm (oh, feel bad commenting that, because I didn't come round to try, and you did all the work), I think the idea was to only merge `pkg/symlink` here, and for `pkg/truncindex`, just creating a copy in containerd would be ok (could of course keep history there as well if useful)

Thanks for providing the steps you took though; let me give it a quick try to repeat with pkg/symlink only

**Comment by thaJeztah** [comment]
> i don't feel that i should not try to "fix" the DCO failure, so leaving it as-is.

Agreed; we can't change history, so no need to fix-up.

Looks like most of them are because of the old `Docker-DCO..` that we used in the past, although the GitHub handle in the first one I picked looks odd (possibly because it was a cherry-pick / carry);

```
Docker-DCO-1.1-Signed-off-by: Michael Crosby <michael@docker.com> (github: vieux)
```

There's also some where it complains about e-mail addresses, wonder if it supports `.mailmap` (not worth the effort though)

**Comment by dims** [comment]
thanks @thaJeztah ! the new PR looks good! ( i had missed a couple of things like stripping out `pkg/` and adding the new package to the Makefile etc. )

**Comment by thaJeztah** [comment]
Thanks for starting the work; your steps helped me getting it done (without having to do a lot of Google-fu 😂)

**Pull request closed without merging**
