### PR TITLE
Add lcow supported signals to windows signal map

### PR DESCRIPTION
**Pull request by katiewasnothere**
This PR addresses the issues discussed in https://github.com/containerd/containerd/pull/6002 to support linux signals for LCOW. 

Signed-off-by: Kathryn Baldauf <kabaldau@microsoft.com>

### CODE REVIEW

**Comment by katiewasnothere** [comment]
@dmcgowan @jterry75 @kzys FYI

**Review by dmcgowan — APPROVED** [review]

**Review by samuelkarp — APPROVED** [review]

**Review by jterry75 — APPROVED** [review]
LGTM

**Comment by katiewasnothere** [comment]
@samuelkarp Does this PR need another sign off? Is there anything blocking merging it?

**Comment by samuelkarp** [comment]
Yes, generally two maintainer LGTMs.

**Review by kzys — APPROVED** [review]

**Comment by katiewasnothere** [comment]
@thaJeztah could you take a look when you get the chance?

**Review by thaJeztah — APPROVED** [review]
LGTM

sorry, I somehow missed this one 😅

**Pull request merged**
